apiVersion: v1
kind: Service
metadata:
  name: whitelist 
  labels:
    component: whitelist
spec:
  selector:
    component: whitelist
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whitelist
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: whitelist
    spec:
      volumes:
       - hostPath:
            path: "/home/ubuntu/whitelist"
         name: src
      containers:
      - name: nginx 
        image: nginx
        volumeMounts:
          - name: src
            mountPath: "/usr/share/nginx/html/"
        ports:
        - containerPort: 80
          protocol: TCP
